// Regression test for Incident #1
// Service: auth-service
// Error Type: SYNTAX_ERROR
// Generated by Subagent Beta (Sentinel) — do not edit manually

import { describe, it, expect } from '@jest/globals';
import fs from 'fs';
import path from 'path';

describe('auth-service — Regression: SYNTAX_ERROR', () => {
  const srcPath = path.join(__dirname, '..', 'src', 'index.ts');
  const configPath = path.join(__dirname, '..', 'config.json');

  it('src/index.ts must not contain chaos injection tokens', () => {
    const content = fs.readFileSync(srcPath, 'utf8');
    expect(content).not.toContain('<<<CHAOS_SYNTAX_ERROR>>>');
    expect(content).not.toContain('CHAOS_SYNTAX_BREAK');
  });

  it('src/index.ts must be valid (no unparseable tokens)', () => {
    const content = fs.readFileSync(srcPath, 'utf8');
    // File should start with a valid TS import or comment
    expect(content.trim().startsWith('import') || content.trim().startsWith('//')).toBe(true);
  });

  it('config.json must be valid JSON', () => {
    const raw = fs.readFileSync(configPath, 'utf8');
    expect(() => JSON.parse(raw)).not.toThrow();
  });

  it('config.json must have required keys', () => {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    expect(config).toHaveProperty('port');
    expect(config).toHaveProperty('name');
  });
});
